apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: devops-assignment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-assignment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        app: devops-assignment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: cnr-2023mt03544
        #image: sanjum016/img-2023mt03544:v2
        image: sanjum016/intern:v2
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-2023mt03544
