apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops-assignment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort